// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <RobertaFunctions.h>   // Open Roberta library
#include <NEPODefs.h>

RobertaFunctions rob;

std::list<double> item;
std::list<bool> item2;
std::list<String> item3;
std::list<unsigned int> item4;
int _led_L = 13;
void setup()
{
    Serial.begin(9600); 
    pinMode(_led_L, OUTPUT);
    item = {5, 5, 5, 5, 5};
    item2 = {true, true, true, true, true};
    item3 = {123, 123, 123, 123, 123};
    item4 = {RGB(51, 204, 0), RGB(51, 204, 0), RGB(51, 204, 0), RGB(51, 204, 0), RGB(51, 204, 0)};
}

void loop()
{
}